### ISSUE TITLE
Authorization header is not necessary for API calls

### ISSUE THREAD

**Issue by vlmaier** [mavifindsbugs/cscolors-extractor#1]
`Authorization` header can be dropped for requests since `Apikey` header is containing the same value and is sufficient for making authorized API calls.

**Comment by mavifindsbugs** [comment]
Thanks for opening the issue. As far as I know the Apikey is used to get past the Supabase Gateway and to access the API itself.

The Authorization Header is used for additional user authorization. I guess these are the same by default when the user is not signed in (the project does have any user functionality).
